export const ACTION_TYPES = {
    ADD_RECIPE: 'ADD_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    EDIT_NAME_USER: 'EDIT_NAME_USER',
    EDIT_EMAIL_USER: 'EDIT_EMAIL_USER',
    ADD_USER_NOTES: 'ADD_USER_NOTES',
};
